apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: coolkit
type: Opaque
data:
  dbname: ZGF0YWJhc2U=
  hostname: c29tZS5yZW1vdGUuZGIuaG9zdA==
  password: c3VwZXJzZWNyZXQxMjM=
  username: ZGItdXNlcg==
